import {
  SquaresFour as SquaresFourIcon,
  Users,
  IdentificationCard,
  Money,
  Barbell as BarbellIcon,
  FileText,
  ShoppingCart,
  Gear,
  List,
  Bell,
  Moon,
  SunDim,
  MagnifyingGlass as MagnifyingGlassIcon,
  SlidersHorizontal,
  Funnel,
  UserPlus,
  FileCloud,
  User,
  EnvelopeSimple,
  Phone,
  WarningCircle,
  Calendar,
  DotsThreeVertical,
  CaretLeft,
  CaretRight,
  CaretDown,
  Stack,
  Wallet,
  PlusCircle,
  ChartLineUp,
  CalendarBlank,
  Clock,
  Pulse,
  UserCircleCheck,
  PiggyBank as PiggyBankIcon,
  TrendUp,
  TrendDown,
  CreditCard,
  Megaphone,
  BoxingGlove as BoxingGloveIcon,
  MapPin,
  SignOut,
  ClipboardText,
  Warning,
  Package,
  Eye,
  PencilSimple,
  Trash,
  Plus,
  QrCode,
  Tag,
  Pulse as PulseIcon,
  ShieldCheck,
  BellRinging,
  Palette,
  Camera,
  CheckCircle,
  LockKey,
  Mailbox as MailboxIcon,
  Monitor as MonitorIcon,
  DeviceMobileCamera as DeviceMobileCameraIcon,
  DeviceTabletCamera as DeviceTabletCameraIcon,
  Laptop as LaptopIcon,
  X,
  X as XIcon,
  ChatCircleText,
  Star,
  ImageSquare,
  Check,

  // Expose as original names for compatibility
  MagnifyingGlass,
  SquaresFour,
  Barbell,
  Car as CarProfileIcon,        // CarProfileIcon → Car (closest Phosphor equivalent)

  // Reports specific icons
  FileText as FileTextIcon,
  ChartLine as ChartLineIcon,
  Calendar as CalendarIcon,
  CalendarDots as CalendarDotsIcon,
  Clock as ClockIcon,
  GearSix as GearSixIcon,
  Files as FilesIcon,

  // Finance specific icons
  Wallet as WalletIcon,
  CurrencyDollar as CurrencyDollarIcon,
  Percent as PercentIcon,
  Money as MoneyIcon,

  // Finance page table icons
  Receipt as ReceiptText,
  DotsThreeVertical as MoreVertical,
} from "@phosphor-icons/react";

export {
  SquaresFourIcon,
  Users,
  IdentificationCard,
  Money,
  BarbellIcon,
  FileText,
  ShoppingCart,
  Gear,
  List,
  Bell,
  Moon,
  SunDim,
  MagnifyingGlassIcon,
  SlidersHorizontal,
  Funnel,
  UserPlus,
  FileCloud,
  User,
  EnvelopeSimple,
  Phone,
  WarningCircle,
  Calendar,
  DotsThreeVertical,
  CaretLeft,
  CaretRight,
  CaretDown,
  Stack,
  Wallet,
  PlusCircle,
  ChartLineUp,
  CalendarBlank,
  Clock,
  Pulse,
  UserCircleCheck,
  PiggyBankIcon,
  TrendUp,
  TrendDown,
  CreditCard,
  Megaphone,
  BoxingGloveIcon,
  MapPin,
  SignOut,
  ClipboardText,
  Warning,
  Package,
  Eye,
  PencilSimple,
  Trash,
  Plus,
  QrCode,
  Tag,
  PulseIcon,
  ShieldCheck,
  BellRinging,
  Palette,
  Camera,
  CheckCircle,
  LockKey,
  MailboxIcon,
  MonitorIcon,
  DeviceMobileCameraIcon,
  DeviceTabletCameraIcon,
  LaptopIcon,
  X,
  XIcon,
  ChatCircleText,
  Star,
  ImageSquare,
  Check,

  MagnifyingGlass,
  SquaresFour,
  Barbell,
  CarProfileIcon,

  // Reports specific icons
  FileTextIcon,
  ChartLineIcon,
  CalendarIcon,
  CalendarDotsIcon,
  ClockIcon,
  GearSixIcon,
  FilesIcon,

  // Finance specific icons
  WalletIcon,
  CurrencyDollarIcon,
  PercentIcon,
  MoneyIcon,

  // Finance page table icons
  ReceiptText,
  MoreVertical,
};
