import {
  SquaresFour as SquaresFourIcon,
  Users,
  IdentificationCard,
  Money,
  Barbell as BarbellIcon,
  FileText,
  ShoppingCart,
  Gear,
  List,
  Bell,
  Moon,
  SunDim,
  MagnifyingGlass as MagnifyingGlassIcon,
  SlidersHorizontal,
  Funnel,
  UserPlus,
  FileCloud,
  User,
  EnvelopeSimple,
  Phone,
  WarningCircle,
  Calendar,
  DotsThreeVertical,
  CaretLeft,
  CaretRight,
  CaretDown,
  UserCircleCheck,
  PiggyBank as PiggyBankIcon,
  TrendUp,
  TrendDown,
  CreditCard,
  Megaphone,
  BoxingGlove as BoxingGloveIcon,
  MapPin,
  SignOut,
  ClipboardText,
  Warning,
  Package,
  Eye,
  PencilSimple,
  Trash,
  Plus,
  QrCode,
  Tag,
  Pulse as PulseIcon,
  ShieldCheck,
  BellRinging,
  Palette,
  Camera,
  CheckCircle,
  LockKey,
  Mailbox as MailboxIcon,
  Monitor as MonitorIcon,
  DeviceMobileCamera as DeviceMobileCameraIcon,
  DeviceTabletCamera as DeviceTabletCameraIcon,
  Laptop as LaptopIcon,
  X as XIcon,
  ChatCircleText,
  Star,
  ImageSquare,
  Check,
  MagnifyingGlass,
  SquaresFour,
  Barbell,
} from "@phosphor-icons/react";

export {
  SquaresFourIcon,
  Users,
  IdentificationCard,
  Money,
  BarbellIcon,
  FileText,
  ShoppingCart,
  Gear,
  List,
  Bell,
  Moon,
  SunDim,
  MagnifyingGlassIcon,
  SlidersHorizontal,
  Funnel,
  UserPlus,
  FileCloud,
  User,
  EnvelopeSimple,
  Phone,
  WarningCircle,
  Calendar,
  DotsThreeVertical,
  CaretLeft,
  CaretRight,
  CaretDown,
  UserCircleCheck,
  PiggyBankIcon,
  TrendUp,
  TrendDown,
  CreditCard,
  Megaphone,
  BoxingGloveIcon,
  MapPin,
  SignOut,
  ClipboardText,
  Warning,
  Package,
  Eye,
  PencilSimple,
  Trash,
  Plus,
  QrCode,
  Tag,
  PulseIcon,
  ShieldCheck,
  BellRinging,
  Palette,
  Camera,
  CheckCircle,
  LockKey,
  MailboxIcon,
  MonitorIcon,
  DeviceMobileCameraIcon,
  DeviceTabletCameraIcon,
  LaptopIcon,
  XIcon,
  ChatCircleText,
  Star,
  ImageSquare,
  Check,
  MagnifyingGlass,
  SquaresFour,
  Barbell,
};